# Generated by Django 4.2.7 on 2023-12-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('faculty', models.CharField(max_length=40)),
                ('grade', models.IntegerField()),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
