# Generated by Django 4.2.7 on 2023-12-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=10)),
                ('fee', models.IntegerField()),
                ('start_date', models.DateField()),
            ],
        ),
    ]
